/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraficoHistograma.java
 *
 * Created on 07-jun-2013, 15:49:08
 */

package intartificial;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.image.BufferedImage;
import java.io.File;


import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;




/**
 *
 * @author Ani Rufinetto
 */
public class GraficoHistogramaEcualizado extends javax.swing.JDialog {
    private BufferedImage _image ;//para la imagen en memoria
    private JFreeChart grafico ;// el grafico
    private Dimension d;//dimension del grafico
   // private File arch=new File("histograma.jpg");;
    private ImageIcon imagen;
    /** Creates new form GraficoHistograma */
    public GraficoHistogramaEcualizado(java.awt.Frame parent, boolean modal,float[] niveles,float[] frecuencias,String name) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
       // ImageIcon imagen=new ImageIcon("histograma.jpg");
       File arch=new File(name);
       crearHistograma(arch,niveles,frecuencias,jLabel3,"Histograma Ecualizado");

       
       //crearHistograma(arch1,frecEcualizadas,jLabel1,"Histograma Ecualizado");
     //  crearHistograma(frecuencias,jLabel1,"Histograma Ecualizado");
       
        // agregamos la imagen al label
      
        /*  imagen1 = new ImageIcon("ecualizacion.jpg");
        // agregamos la imagen al label
        jLabel1.setIcon(imagen1);
        //AGREGAMOS LA ETIQUETA QUE CONTIENE LA IMAGEN AL FRAME
         this.getContentPane().add(jLabel1);*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



private void crearHistograma(File arch,float[] niveles,float[] g, JLabel jl,String titulo)
    {
       JFreeChart chart;


      DefaultCategoryDataset dataset = new DefaultCategoryDataset();
      try{

      for(int i=0;i<g.length;i++)
        {
            float x=g[i];
            if(niveles[i]>0)
            {
                Comparable j = Math.floor(niveles[i] * 100.0) / 100.0;
            //Comparable j=Math.round(niveles[i]*100.0)/100.0;
           // Comparable j=Math.ceil(niveles[i]*100.0)/100.0;

            dataset.setValue(x, "Frecuencia", j);
            }
          }

      chart = ChartFactory.createBarChart(titulo,"Niveles de Gris", "Frecuencia", dataset, PlotOrientation.VERTICAL, false,true, false);

       CategoryPlot plot =(CategoryPlot) chart.getPlot();
           BarRenderer renderer = (BarRenderer)plot.getRenderer();
    renderer.setDrawBarOutline(false);
    //Dar color a cada barra
    GradientPaint gp0= new GradientPaint(0.0f,0.0f,Color.white,0.0f,0.0f,new Color(0,0,64));

    renderer.setSeriesPaint(0,gp0);
      ChartUtilities.saveChartAsJPEG(arch, chart, 500, 250);

       _image = chart.createBufferedImage(720,250);
        jl.setIcon(new ImageIcon(_image));
        //AGREGAMOS LA ETIQUETA QUE CONTIENE LA IMAGEN AL FRAME
        this.getContentPane().add(jl);

      }

    catch (Exception e) {
       System.err.println("Error creando grafico.");
    }
     
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
