/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Filtros.java
 *
 * Created on 07-dic-2012, 15:12:52
 */

package intartificial;


import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import  java.applet.Applet;
/**
 *
 * @author Ani Rufinetto
 */
public class Filtros extends javax.swing.JApplet {

    /** Initializes the applet Filtros */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    
                    buttonGroup1.add(radioButtonGenerar);
                    buttonGroup1.add(radioButtonIngresar);
                 //   tableFiltradaMedia.setVisible(false);
                   //  tableFiltradaMediana.setVisible(false);
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboVentana = new javax.swing.JComboBox();
        comboFilas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableImagen = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        comboColumnas = new javax.swing.JComboBox();
        radioButtonGenerar = new javax.swing.JRadioButton();
        radioButtonIngresar = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFiltradaMediana = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFiltradaMedia = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setStub(null);

        jLabel2.setText("Seleccionar el tamaño de  la ventana:");

        comboVentana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x1", "3x3", "3x5", "5x1", "5x3", "5x5", "7x1" }));
        comboVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVentanaActionPerformed(evt);
            }
        });

        comboFilas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        comboFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilasActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccionar la fila desde donde comenzar:");

        tableImagen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableImagen);
        tableImagen.getColumnModel().getColumn(0).setResizable(false);
        tableImagen.getColumnModel().getColumn(1).setResizable(false);
        tableImagen.getColumnModel().getColumn(2).setResizable(false);
        tableImagen.getColumnModel().getColumn(3).setResizable(false);
        tableImagen.getColumnModel().getColumn(4).setResizable(false);
        tableImagen.getColumnModel().getColumn(5).setResizable(false);
        tableImagen.getColumnModel().getColumn(6).setResizable(false);
        tableImagen.getColumnModel().getColumn(7).setResizable(false);
        tableImagen.getColumnModel().getColumn(8).setResizable(false);
        tableImagen.getColumnModel().getColumn(9).setResizable(false);
        tableImagen.getColumnModel().getColumn(10).setResizable(false);
        tableImagen.getColumnModel().getColumn(11).setResizable(false);

        jLabel4.setText("Resultados:");

        jLabel5.setText("Valor de Media:");

        jLabel6.setText("Valor de Mediana:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Filtro de la Media");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Filtro de la Mediana");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccionar la columna desde donde comenzar:");

        comboColumnas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        comboColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColumnasActionPerformed(evt);
            }
        });

        radioButtonGenerar.setText("Generar Imagen");
        radioButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenerarActionPerformed(evt);
            }
        });

        radioButtonIngresar.setText("Ingresar Imagen");
        radioButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonIngresarActionPerformed(evt);
            }
        });

        tableFiltradaMediana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableFiltradaMediana);

        tableFiltradaMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableFiltradaMedia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboColumnas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboFilas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonIngresar)
                            .addComponent(radioButtonGenerar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(radioButtonGenerar))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonIngresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jCheckBox1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE))
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFilasActionPerformed

    private void comboVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVentanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVentanaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here

         cargarPorcionImagen();
         calculos();
        crearTableResultados();

        /*  String ventanaSeleccionada=(String)comboVentana.getSelectedItem();
      int column=Integer.parseInt(ventanaSeleccionada.substring(0,1));
      int row=Integer.parseInt(ventanaSeleccionada.substring(2,3));
        for(int i=0;i<column;i++)
        {

          TableColumn col=new TableColumn();
         tableImagenFiltrada.addColumn(col);
        // Vector vec=new Vector(row);
       


        }*/
       
     
}//GEN-LAST:event_jButton1ActionPerformed


private void crearTableResultados()
    {

      String ventanaSeleccionada=(String)comboVentana.getSelectedItem();
      int column=Integer.parseInt(ventanaSeleccionada.substring(0,1));
      int row=Integer.parseInt(ventanaSeleccionada.substring(2,3));
      int z=0;
      DefaultTableModel model=new DefaultTableModel();
      
      for (int i = 0; i < column; i++)
          {
          model.addColumn("");
           for(int j=0;j<row;j++)
           {
             Vector v=new Vector();
               try{

                   v.add(porcionImagen[z]);
                   model.addRow(v);
                  // tableFiltradaMedia.setValueAt(porcionImagen[z], i, j);
                   z++;

                    if(z==(porcionImagen.length-1)/2)
                       {

                       
                      String.valueOf(tableFiltradaMedia.getValueAt(i,j));
                       }
         //  Component cell = super.getTableCellRendererComponent(tableFiltradaMedia, porcionImagen[z], false, false, i, j);

               }
               catch(Exception e){}

           }


          }
  tableFiltradaMedia.setModel(model);

    }

    private void calculos()
    {

       if(jCheckBox1.isSelected()) {
            int media=filtro.calcularMedia(porcionImagen);
            porcionImagen[(porcionImagen.length-1)/2]=media;
            jTextField2.setText(""+media);

          //  porcionImagen[(porcionImagen.length-1)/2]=media;
           /* for(int i=0;i<porcionImagen.length;i++) {
                if(i==0) {
                   // jTextField2.setText(""+porcionImagen[i]);} else {
                   // jTextField2.setText(jTextField2.getText() + "-" + porcionImagen[i]);
                    }*/
           // }
        }
        if(jCheckBox3.isSelected()) {
            int mediana=filtro.calcularMediana(porcionImagen);
            porcionImagen[(porcionImagen.length-1)/2]=mediana;
            jTextField3.setText(""+mediana);
           /* porcionImagen[(porcionImagen.length-1)/2]=mediana;
            for(int i=0;i<porcionImagen.length;i++) {
                if(i==0) {
                   // jTextField3.setText(""+porcionImagen[i]);} else {
                  //  jTextField3.setText(jTextField3.getText() + "-" + porcionImagen[i]);
                    }*/
            }

    }

    private void cargarPorcionImagen()
    {

      String ventanaSeleccionada=(String)comboVentana.getSelectedItem();
      int column=Integer.parseInt(ventanaSeleccionada.substring(0,1));
      int row=Integer.parseInt(ventanaSeleccionada.substring(2,3));
      int z=0;
      String columnSelected=(String)comboColumnas.getSelectedItem();
      int columnFrom=Integer.parseInt(columnSelected);
      String rowSelected=(String)comboFilas.getSelectedItem();
      int rowFrom=Integer.parseInt(rowSelected);
      porcionImagen= new int[row*column];
      if((column+columnFrom)<=12)
      {
          for (int i = rowFrom; i < row+rowFrom; i++)
          {
           for(int j=columnFrom;j<column+columnFrom;j++)
           {
               try{
               int currentValue=Integer.parseInt(tableImagen.getValueAt(i, j).toString());
               porcionImagen[z]=currentValue;
              z++;
               }
               catch(Exception e){}

           }


          }

        }
 else
      {System.out.println("Ingreseotracombinacion");}
        

      

    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void comboColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColumnasActionPerformed

    private void radioButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonIngresarActionPerformed
        // TODO add your handling code here:
     jTextField2.setText("");
     jTextField3.setText("");

     for(int i=0;i<12;i++)
      {
      for(int j=0;j<6;j++)
      {

        tableImagen.setValueAt(null, j, i);

      }

      }
    }//GEN-LAST:event_radioButtonIngresarActionPerformed

    private void radioButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenerarActionPerformed
        // TODO add your handling code here:
     jTextField2.setText("");
     jTextField3.setText("");
     generarNumeros();

    }//GEN-LAST:event_radioButtonGenerarActionPerformed

 private void generarNumeros()
    {
      for(int i=0;i<12;i++)
      {
      for(int j=0;j<6;j++)
      {
        int numero=(int) (Math.random() * 60);
        tableImagen.setValueAt(numero, j, i);

      }

      }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboColumnas;
    private javax.swing.JComboBox comboFilas;
    private javax.swing.JComboBox comboVentana;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton radioButtonGenerar;
    private javax.swing.JRadioButton radioButtonIngresar;
    private javax.swing.JTable tableFiltradaMedia;
    private javax.swing.JTable tableFiltradaMediana;
    private javax.swing.JTable tableImagen;
    // End of variables declaration//GEN-END:variables
private int[] porcionImagen;
private Filtro filtro=new Filtro();

}
